# Generated by Django 3.1.3 on 2021-06-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='null', upload_to='img'),
        ),
    ]
